name: Adex CLI
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  code-check:
    name: Code Checks
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Cargo cache
        uses: ./.github/actions/cargo-cache

      - name: Start checking code format and lint
        run: |
          cargo fmt --manifest-path ./mm2src/adex_cli/Cargo.toml --all -- --check
          cargo clippy --manifest-path ./mm2src/adex_cli/Cargo.toml --all-targets --all-features -- --D warnings

      - name: Start building
        run: |
          cargo build --manifest-path ./mm2src/adex_cli/Cargo.toml

      - name: Start testing
        run: |
          cargo test --manifest-path ./mm2src/adex_cli/Cargo.toml --no-fail-fast
