name: Format and Lint
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  fmt-and-lint:
    name: Style Checks
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: |
          rustup toolchain install nightly-2022-10-29 --no-self-update --profile=minimal --component rustfmt clippy
          rustup default nightly-2022-10-29

      - name: Install OS dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update 
          sudo apt-get -y install libudev-dev

      - name: Cargo cache
        uses: ./.github/actions/cargo-cache

      - name: fmt check
        # Format checks aren't OS dependant.
        if: matrix.os == 'ubuntu-latest'
        run: cargo fmt -- --check

      - name: clippy lint
        run: cargo clippy --all-targets --all-features -- --D warnings

  wasm-lint:
    name: Style Checks
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: |
          rustup toolchain install nightly-2022-10-29 --no-self-update --profile=minimal --component clippy
          rustup default nightly-2022-10-29
          rustup target add wasm32-unknown-unknown

      - name: Cargo cache
        uses: ./.github/actions/cargo-cache

      - name: clippy lint
        run: cargo clippy --target wasm32-unknown-unknown -- --D warnings
